#!/usr/bin/python
import hal, time
h = hal.component("laser_card")
h.newpin("in", hal.HAL_FLOAT, hal.HAL_IN)
h.newpin("out", hal.HAL_FLOAT, hal.HAL_OUT)
h.ready()
try:
    while 1:
        pass
except KeyboardInterrupt:
    raise SystemExit
